### PR TITLE
Update to NodeJS 16 as 12 will be deprecated

### LINKED ISSUE #21: NodeJS v12 is deprecated
When using this action GitHub warns that NodeJS v12 is deprecated:

`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: winify-ag/setup-phraseapp`

### PR DESCRIPTION
**Pull request by skeeping**
Closes #21

### CODE REVIEW

**Review by jetaix — APPROVED** [review]

**Review by youssdevx — APPROVED** [review]

**Comment by irosgrim** [comment]
is anyone merging this PR ?

**Comment by tatsiana-IKEA** [comment]
Is anyone merging this PR?

**Comment by Babymac** [comment]
Is anyone merging this PR?

**Comment by youssdevx** [comment]
@pedpess @iamandrewluca could you please approve and merge this?

**Comment by henrikra** [comment]
Don't hold your breath since the company who made this repo (Winify AG); even their website is down so I guess they went bankrupt or something like that. Website: http://winify.com/

**Comment by unrevised6419** [comment]
Hi folks, maintainer here!

I can take a look at this over the weekend, and update it to the last best practices.

ps: I would gladly pass this repo to the Phrase team maybe. I don't use it anymore 🤔 

ps2: Yes, the company does not exist anymore.

**Comment by henrikra** [comment]
> Hi folks, maintainer here!
> 
> I can take a look at this over the weekend, and update it to the last best practices.
> 
> ps: I would gladly pass this repo to the Phrase team maybe. I don't use it anymore 🤔
> 
> ps2: Yes, the company does not exist anymore.

Friday magic 🪄

**Comment by henrikra** [comment]
@iamandrewluca Thx for the merge! Can you add @pedpess with write access to this repo? He is already contributor and active (I know him). This way we don't have to wait months for chore updates like this.

**Comment by henrikra** [comment]
@iamandrewluca Did you publish the new version already? I am getting this error when trying with v3:

Error: Unable to resolve action `winify-ag/setup-phraseapp@v3`, unable to find version `v3`

**Comment by unrevised6419** [comment]
@henrikra try again, I forgot to push the tag 🤦🏼

**Comment by unrevised6419** [comment]
I opened an issue, in `phrase-cli` repo to take this action under their wing. Let's see what they say.

https://github.com/phrase/phrase-cli/issues/119

**Comment by unrevised6419** [comment]
Phrase took the repo under their organisation https://github.com/phrase/setup-cli
Migration is just changing the action name.
This repo won't be maintained anymore.

**Pull request merged**
